version: '3'
services:
  rabbit:
    image: "rabbitmq:3-management"
    ports:
     - "5672:5672"
     - "15672:15672"
    volumes:
     - rabbitmq:/var/lib/rabbitmq
    networks:
      - webmthread
  mongo:
    image: "mongo:latest"
    ports:
     - "27017:27017"
    volumes:
     - db:/data/db
    networks:
      - webmthread
  finder:
    build:
     context: .
     dockerfile: ./finder/Dockerfile
    networks:
      - webmthread
    depends_on:
      - rabbit
      - db
  webm2gif:
    build:
     context: .
     dockerfile: ./webm2gif/Dockerfile
    networks:
      - webmthread
    depends_on:
      - rabbit
      - db
  db:
    build:
     context: .
     dockerfile: ./db/Dockerfile
    networks:
      - webmthread
    depends_on:
      - rabbit
      - mongo
volumes:
  rabbitmq:
  db:
networks:
  webmthread:
